### ISSUE TITLE
message liquid variables

### ISSUE THREAD

**Issue by 743v45** [ptkdev/json-token-replace#9]
### Feature description

I ready to get the message at path of pkg, but only one layer can be obtained.

package.json

```json
{
  "engines": {
    "node": ">= 12.0.0"
  }
}
```

 [![Node.js](https://img.shields.io/badge/Node.js->=%2012.0.0-brightgreen.svg?style=plastic&logo=)](https://nodejs.org/en/)

`all-shields-cli` should support `message = "{{engines.node}}"` for generating the badge above.

[`lodash.get()`](https://lodash.com/docs/4.17.15#get) is a good way to solve the problem.

thx

**Comment by ptkdev** [comment]
PR are welcome.

**Comment by ptkdev** [comment]
@743v45 hi!
Now [all-shields-cli](https://github.com/ptkdev/all-shields-cli) work without this dependence.
